In [25]:
import torch
import numpy as np

In [4]:
x = torch.ones(3, 3)
y = torch.rand(3, 3)


tensor([[1.4958, 1.8773, 1.6080],
        [1.2631, 1.9915, 1.1615],
        [1.0674, 1.2704, 1.4683]])


In [14]:
#Print Size
x.size()

torch.Size([3, 3])

In [5]:
#Basic Operations
z = x +y
z = x-y
z = x*y
z = x/y

#Inplace
y.add_(x)
y.sub_(x)
y.mul_(x)
y.div_(x)

tensor([[0.4958, 0.8773, 0.6080],
        [0.2631, 0.9915, 0.1615],
        [0.0674, 0.2704, 0.4683]])

In [13]:
#Slicing
print(x[1:, :2])

tensor([[1., 1.],
        [1., 1.]])


In [19]:
#reshaping
y = x.view(-1)
print(y)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [26]:
# Numpy tp Torch and Vice Versa
# here both array points to the same memory. Changing one will affect another

a = torch.ones(5)
print(a)
na = a.numpy()
print(na)

na = np.ones(5)
print(na)
a = torch.from_numpy(na)
print(a)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [28]:
#Check if GPU is available
a = torch.cuda.is_available()
print(a)
if a:
    device = torch.device("cuda")
    x = torch.ones(5, device= device)
    print(x)

True
tensor([1., 1., 1., 1., 1.], device='cuda:0')


In [29]:
#requires_grad
#this tells torch that torch will need to find gradient in later stages
x = torch.ones(5, requires_grad=True)
print(x)


tensor([1., 1., 1., 1., 1.], requires_grad=True)
