In [1]:
import torch


In [4]:
#create tensor with gradients requires
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.4417,  1.7170,  0.0274], requires_grad=True)


In [5]:
#addition with backpropogation
y = x + 2
print(y)

tensor([1.5583, 3.7170, 2.0274], grad_fn=<AddBackward0>)


In [10]:
##Adding more functions
z = y*y*2
#z = z.mean()
print(z)


tensor([ 4.8569, 27.6328,  8.2207], grad_fn=<MulBackward0>)


In [12]:
#computinng gradients by layer
#After computation gradients are stored in first layer
#grad can be implicitly created only for scalar outputs
z.backward()
print(x.grad)

#if we havent computed mean, then
v = torch.tensor(3, dtype=torch.float32)
z.backward(v)
print(x.grad)

RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([]) and output[0] has a shape of torch.Size([3]).

In [13]:
#remove require grad

#this will remove require_grad for the current tensor.
x.requires_grad(False)

#This will create new tensor with same values but doesnt require the gradients
x.detach()

#or start the code in
with torch.no_grad():
    pass

TypeError: 'bool' object is not callable

In [20]:
#sample training
# we need to clear the gradient in every loop, otherwise it will keep adding the gradiet value to the current sum

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    
    model_output.backward()
    
    print(weights.grad)
    weights.grad.zero_()
    

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [21]:
#sample training
# Using optimzers in the training.

weights = torch.ones(4, requires_grad=True)

optimizer = torch.optim.SGD(weights, lr=0.01)
optimizer.step()
optimizer.zero_grad()

#params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor

TypeError: params argument given to the optimizer should be an iterable of Tensors or dicts, but got torch.FloatTensor